### ISSUE TITLE
extension luanch error

### ISSUE THREAD

**Issue by b0123456789** [Tommimon/add-to-desktop#14]
fedora 35,gnome-shell. 41.4-1.fc35

error:
Type name Gjs_add-to-desktop_tommimon_github_com_shortcutMaker_CustomIcon is already registered

**Comment by Tommimon** [comment]
Hi, where are you getting this error from?

Can you please include the log from `journalctl -o cat /usr/bin/gnome-shell`? just run this command and post the relevant part related to this extension.

**Comment by b0123456789** [comment]
[gnome-shell.log](https://github.com/Tommimon/add-to-desktop/files/8195523/gnome-shell.log)

Here is log file.

**Comment by b0123456789** [comment]
Message "Type name Gjs_add-to-desktop_tommimon_github_com_shortcutMaker_CustomIcon is already registered"  appear many times.

**Comment by b0123456789** [comment]
This extension installed in ~/.local/share/gnome-shell/extensions/.
It is now working after remove extension file on extension  dir and reinstall from extention website.
Thx
