### ISSUE TITLE
add chinese support

### ISSUE THREAD

**Issue by b0123456789** [Tommimon/add-to-desktop#15]
System build in memu item will display correct chinese. but it alway  display "add to destop" in chinese environment.

**Comment by Tommimon** [comment]
Unfortunately Chinese is not yet supported by this extension.
If you want to contribute by translating it to Chinese please open a pull request for that feature.

The [Dutch translation](https://github.com/Tommimon/add-to-desktop/pull/5) pull request is a good starting point but please create a new branch specific for Chinese translation.

**Comment by b0123456789** [comment]
I already pull a request . please  check.

**Comment by Tommimon** [comment]
Chinese will be published in the next release, I expect it to be out in a couple of weeks.
