### ISSUE TITLE
Add Spanish translation

### ISSUE THREAD

**Issue by ramiroaisen** [Tommimon/add-to-desktop#20]
## Language Data
Language name: Spanish
Language code: es
Plural Forms (optional):

## Translator Data
Translator username: ramiroaisen
Translator email: ramiroaisen@gmail.com

## Translation
Add to Desktop: Añadir al Escritorio

Fill the form without changing the structure, Refer to issue #18 for an example of how to fill this template.

**Comment by Tommimon** [comment]
Hi, this extension has a spanish translation already, it's slightly different from the version you gave here.

Do you think this is a better translation? Are you asking to update it?
