### ISSUE TITLE
Software installed via flatpak, no option to add to desktop icons

### ISSUE THREAD

**Issue by OneSeven** [Tommimon/add-to-desktop#23]
Can it be compatible with flatpak software?

**Comment by Tommimon** [comment]
If you want to use add-to-desktop alongside flatpak apps, then the answer is yes, you should be able to create shortcuts for each flatpak app and launch them without any problem.

If you want to install add-to-desktop via faltpak, then no, I don't know if in theory is possible but is not standard to use package managers for GNOME extensions, I've never seen one providing this option.

The intended installation methods are listed in the [README](https://github.com/Tommimon/add-to-desktop#readme). Another way to install GNOME extensions is to use the [official extensions website](https://extensions.gnome.org/#).

I have no plans to support any other installation method.
