### ISSUE TITLE
Add Brazilian translation

### ISSUE THREAD

**Issue by akihiko544** [Tommimon/add-to-desktop#26]
### Language Name

Brazilian Portuguese

### Language Code

pt_BR

### Username

Lucas Ramos

### Email

lucasrssoares6@gmail.com

### Add to Desktop

Adicionar a Área de Trabalho

**Comment by akihiko544** [comment]
# Brazilian Portuguese translations for add-to-desktop package.
# Copyright (C) 2020-2023 the add-to-desktop's copyright holder
# This file is distributed under the same license as the add-to-desktop package.
# Tommimon <tommimon@gmail.com>, 2020.
#
msgid ""
msgstr ""
"Project-Id-Version: add-to-desktop@tommimon.github.com\n"
"Report-Msgid-Bugs-To: https://github.com/Tommimon/add-to-desktop\n"
"POT-Creation-Date: 2023-04-28 10:40+0000\n"
"PO-Revision-Date: 2023-04-28 10:40+0000\n"
"Last-Translator: Tommimon <tommimon@gmail.com>\n"
"Language-Team: BrazilianPortuguese\n"
"Language: pt-br\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"

#: shortcutMaker.js:49
msgid "Add to Desktop"
msgstr "Adicionar a Área de Trabalho"

**Comment by Tommimon** [comment]
Thanks for the translation. Will be included in next release.

**Comment by Tommimon** [comment]
You can download [v11](https://github.com/Tommimon/add-to-desktop/releases/tag/v11) now to have Brazilian translation.
