### ISSUE TITLE
No compatibility

### ISSUE THREAD

**Issue by tremola89** [Tommimon/add-to-desktop#32]
I get the following error message when installing the extension:
"This extension is not compatible with your current GNOME version."
I am using the current ubuntu version 22.04.4 LTS and GNOME-Version 42.9.

**Comment by Tommimon** [comment]
Which version of Add to Desktop are you installing? Only versions from 7 to 10 are compatible with GNOME 42, check if one of those works for you.

If you are having trouble finding the version number of the extension, look in the `metadata.json` file.

**Comment by tremola89** [comment]
I had version 12 installed. Now I have tried version 10 and it works without errors. Thank you very much for your detailed information.

**Comment by Tommimon** [comment]
I'm glad it solved your problem!
