### ISSUE TITLE
Not working on GNOME 41

### ISSUE THREAD

**Issue by Survolog** [Tommimon/add-to-desktop#9]
Error: class heritage parentMenu is not an object or null
I tried replacing "AppIconMenu" with "AppMenu" in the code. This is enough to enable/disable the extension without error (with set shell-version to 41), but it is not enough for the menu to work.

**Comment by Tommimon** [comment]
You are right: in GNOME 41 they removed "AppIconMenu" and used "AppMenu" instead.

Unfortunately just swapping the name isn't enough because "AppMenu" is missing methods that we use for the Add to Desktop button.

I have to find a way to build the button using the "AppMenu" methods.

Expect this to be done in a few days, as soon as I can get my pc ready to test on GNOME 41.

**Comment by Survolog** [comment]
Advance thanks.
To display desktop icons on GNOME 41, I use nemo (from Mate).
I found a new menu in dash-to-panel with this PR: https://github.com/home-sweet-gnome/dash-to-panel/pull/1506
Maybe this will help.

**Comment by Tommimon** [comment]
Sorry but it's taking longer than I thought.

As you can see on the GNOME 41 branch I did the modifications I intended to do but it still doesen't work. I'm keeping working on it and I hope I will find the issue soon.

**Comment by Tommimon** [comment]
Con you confirm that commit https://github.com/Tommimon/add-to-desktop/commit/f2e3f1f78ff98421c7d7958e784262642ebd3134 works on GNOME 41?

Needs a restart after enabling or disabling the extension.

**Comment by Survolog** [comment]
It works! But need
```
-        popupMenu(side = St.Side.LEFT)
+        popupMenu(side = St.Side.LEFT) {
```
in  shortcutMaker.js

However, restarting the extension does not work for me.
It writes
`Type name Gjs_add-to-desktop_tommimon_github_com_shortcutMaker_CustomIcon is already registered`
I do not know why. But this is a minor bug, I think.

**Comment by Tommimon** [comment]
I added the missing bracket, thanks! don't know how this happened.

Since it now works on GNOME 41 I'm closing the issue, version 6 will include those changes.
